### ISSUE TITLE
Basic keyboard support working

### ISSUE THREAD

**Issue by krschacht** [hostedgpt/hostedgpt#25]
- [ ] `Cmd+Enter` to submit a chat
- [ ] Focus the chat input with the existing shortcut + `/`
- [ ] Close the sidebar with the existing shortcut + `Cmd+.`
- [ ] Something to start a new conversation

https://www.stimulus-components.com/docs
https://github.com/stimulus-use/stimulus-use

**Comment by robacarp** [comment]
@krschacht On OpenAI I notice these behaviors:

- `Enter` with the input focused sends the message
- `Shift+Enter` behaves as an enter key should
- `Shift+Esc` focuses chat input
- `Cmd+Shift+S` toggles the sidebar
- `Cmd+Shift+O` starts a new conversation

**Comment by krschacht** [comment]
@robacarp its good for us to support the ones that ChatGPT already does, but I do think we should add / and cmd+. since those are a lot more common.

**Comment by robacarp** [comment]
Oh yes, I agree. I was just documenting what the existing behaviors are.

The only conflict really is that in ChatGPT the enter key submits the chat by default -- if we retain that functionality, it means we don't need Cmd-Enter.

**Comment by krschacht** [comment]
Let’s retain their behavior with enter
